language: swift

cache:
    - bundler
    - cocoapods

before_install:
    - rm -f Podfile.lock
    - pod update

osx_image:
    - xcode10.1
    - xcode10.2
    - xcode10.3
    - xcode11
    - xcode11.1
    - xcode11.2
    - xcode11.3
    - xcode11.4
    - xcode11.5
    - xcode11.6
    - xcode12
    - xcode12.2
    - xcode12.3
    - xcode12.4
    - xcode12.5

script: ./bin/build_app.sh
